import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Grid from "@mui/material/Grid";
import "./globals.css";
import { Logout } from "@/components/Logout";
import Search from "@/components/Search";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Grid
        container
        component="body"
        className={inter.className}
        maxWidth="xs"
      >
        <Search />
        <Logout />
        {children}
      </Grid>
    </html>
  );
}
